version: '2'
services:

  common_db:
    image: postgres:10.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE=project
      - DATABASE_USER=docker
      - DATABASE_PASSWORD=docker
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
      - app-network

volumes:
  postgres-data:
networks:
  app-network: